# Setup
title:               'Today I Learned'
tagline:             'Notes to self about software development'
description:         ''
url:                 'https://KevinDelaFuente.github.io/'
baseurl:             'til/'
paginate:            5
permalink:           pretty

# About/contact
author:               
  name:              Kevin De la Fuente
  url:               https://www.linkedin.com/in/kevindelafuente/
  email:             kevin.delafuente@chicagobooth.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
